### ISSUE TITLE
Versions 1.8.0+ from NPM are not working

### ISSUE THREAD

**Issue by riomus** [tomasbjerre/violation-comments-to-github-command-line#2]
After installing any version 1.8+ from NPM, any execution results in exception:

Exception in thread "main" java.lang.IllegalArgumentException: -comment-only-changed-files was not found in this result at all. Did you perhaps forget to add it to withArguments(...)?
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:119)
	at shadow.se.softhouse.jargo.ParsedArguments.get(ParsedArguments.java:75)
	at se.bjurr.violations.main.Runner.main(Runner.java:158)
	at se.bjurr.violations.main.Main.main(Main.java:6)

Java: 11
Linux

**Comment by tomasbjerre** [comment]
What is the exact command you are using?

**Comment by riomus** [comment]
My command is:
```
   1   │ #!/usr/bin/env bash
   2   │ 
   3   │ violation-comments-to-gitlab-command-line \
   4   │  -at "${GITLAB_API_TOKEN}" \
   5   │  -pi "${GITLAB_PROJECT_ID}" \
   6   │  -mr-iid "${CI_MERGE_REQUEST_IID}" \
   7   │  -v "CHECKSTYLE" "." ".*scalastyle-result\.xml$" "Scalastyle" 

```

But executing a command from sample results with same error (I know that sample command will not work, but in version 1.7.0 i get proper auth error)
